= Revolut REST API Design

The purpose of this project is to define a basic REST API for money transfers between internal users/accounts.

== Technology Stack

Spring Boot makes it easy to create Spring-powered, production-grade applications and services with absolute minimum fuss. It takes an opinionated view of the Spring platform so that new and existing users can quickly get to the bits they need.

This project uses the following modules / libraries:

* Latest version of Spring Boot
* Spring 4
* Java 8
* JPA for data persistence
* Embedded H2 database
* Spring HATEOAS for Hypermedia

This project also includes Unit tests and Integration tests. The approach is to have a separation of concerns between the different layers of the application. This way, there are three layers in the application:

* Controller layer: The TransactionsController contains the necessary logic to manage the transfer.
* Service layer: This project uses the Spring container to inject depedencies, using interfaces to have the posibility to choose between different implementations. For this layer, the interface TransferService provides all the necessary services to work with transactions.
* Repository layer: It is the DAO. It uses JPA repositories. The TransferService implementation has two colaborators: AccountRepository (to get the internal accounts) and a TransferRepository (to store the transaction).

== REST API implementation

The REST APIs provide programmatic access to create new transfers. The functionality defined is very basic, it is only posible to make internal transactions, that is make a trasfer within the system.

=== Resources

The only resource defined is _transactions_.

=== Content Negotiation

For content negotiation, by default it uses the value of the *Accept Header*. The could change this configuration as needed, using for example a URI suffix and additional request parameter or a customized HTTP header.

=== Operations

==== POST /transactions

**Request Body**

```json
{
	"sourceAccount": "<source account number>",
	"targetAccount": "<target account number>",
	"amount": <amount>
}
```

A POST request like that creates one transaction in the system.

**Example with curl**

----
curl -H "Content-Type: application/json" -X POST -d '{"sourceAccount":"0","targetAccount":"1", "amount":5.0}' http://localhost:8080/transactions
----

Fields description:

* sourceAccount is the source account number.
* targetAccount is the target account number.
* amount is the desired amoung to be transfered.

**Output**
```json
{
  "status":"PENDING",
  "_links":
  {
    "self":
	  {
	    "href":"http://localhost:8080/transactions/2"
	  }
  }
}
```

**Error codes**

400 BAD REQUEST

There are multiple reasons to obtain this error code:

- If the source account number does not belong to the current user.
- Source account and target accounts must be non null and non empty values.
- Amount must be positive.
- Source and target accounts must be different.

501 NOT IMPLEMENTED

External transfers are not allowed. The system will check if the target account is an internal one.


==== PUT /transactions/<transactionID>

After creating a new transaction, it must be processed. To do that a PUT request must be sent to the server using the URI returned by the first operation. For example:

**Example with curl**

----
curl -H "Content-Type : application/json" -X PUT http://localhost:8080/transactions/<transactionId>
----

**Output**

```json
{
  "status":"COMPLETED",
  "_links":
  {
    "self":
    {
      "href":"http://localhost:8080/transactions/2"
    }
  }
}
```

**Error codes**
400 BAD REQUEST
There are some reason obtaining this status code:

- The <transactionId> is not found in the system
- Transaction has been processed before

=== Errors

There is one central piece to manage the error within the controllers. This class is the RevolutControllerAdvice and provides all the information for the error. The implementation contains only a message, but it would be necessary to add more information like a developerMessage with more technical information, status code or manage errors as another resource providing a link with an identifier.

The response could return one or multiple errors:

```json
  [
    {
      "message": "Invalid value for argument sourceAccount and description: Source account number is null or empty"
    },
    {
      "message": "Invalid value for argument targetAccount and description: Target account number is null or empty"
    }
  ]
```

=== Links and Hypermedia

It is a good practice to include links inside the resource to implement HATEOAS. For future features, it is a good idea to implement OPTIONS request to discover the API.


== Run the application

To run the application, execute:

----
mvn package && java -jar target/revolut-0.0.1-SNAPSHOT.jar

----

